name: Ecotropolis
main: us.danielpmc.ecotropolis.main
version: 2.0
author: danielpmc
commands:
   heal:
      description: Heal yourself!
      usage: /heal
   efly:
      description: Enable Fly!
      usage: /efly
   dfly:
      description: Disable Fly!
      usage: /dfly
   feed:
      description: Feed yourself!
      usage: /feed
   gmc:
      description: Gamemode creative
      usage: /gmc
   gms:
      description: Gamemode survival
      usage: /gms
   tp:
      description: teleport to a player!
      usage: /tp
   discord:
      description: link to our discord
      usage: /discord
   website:
      description: link to our website
      usage: /website
   ecoabout:
      description: Info about plugin
      usage: /ecoabout
   etps:
      description: Gets the current ticks per second for the server!
      usage: /etps
   eban:
      description: BAN BAN BANNNNNNNNNNNN!
   eunban:
      description: oh meh god unban??